- .github/workflows/createrelease.yml
- antragsnr/package-lock.json
- antragsnr/package.json
- buildScript.js
- csv/package-lock.json
- csv/package.json
- fieldtofile/package-lock.json
- fieldtofile/package.json
- ics/package-lock.json
- ics/package.json
- intrafox/package-lock.json
- intrafox/package.json
- math/package-lock.json
- math/package.json
- mssql/package-lock.json
- mssql/package.json
- mysql/package-lock.json
- mysql/package.json
- package-lock.json
- package.json
- report/package-lock.json
- report/package.json
- roxFile/package-lock.json
- roxFile/package.json
- sap/package-lock.json
- sap/package.json
- servicetemplate/package-lock.json
- servicetemplate/package.json
Fixed missing contents of node_modules in release zip
> Release contains correct dependencies

- report/createReport-config.tsx
> Fixed typo and wording in Report service

- antragsnr/package-lock.json
- antragsnr/package.json
- buildScript.js
- csv/package-lock.json
- csv/package.json
- fieldtofile/package-lock.json
- fieldtofile/package.json
- ics/package-lock.json
- ics/package.json
- intrafox/package-lock.json
- intrafox/package.json
- math/package-lock.json
- math/package.json
- mssql/package-lock.json
- mssql/package.json
- mysql/package-lock.json
- mysql/package.json
- package-lock.json
- package.json
- report/package-lock.json
- report/package.json
- roxFile/package-lock.json
- roxFile/package.json
- sap/package-lock.json
- sap/package.json
- servicetemplate/package-lock.json
- servicetemplate/package.json
- startinstance/package-lock.json
- startinstance/package.json
* Updated to SDK with newer hapi version
* Installed updated typedefs for every package
> Updated hapi

- sap/package.json
* Fix that node_modules are included in built service .zip
> Fixed build paths for SAP service

- antragsnr/package-lock.json
- antragsnr/package.json
- csv/package-lock.json
- csv/package.json
- fieldtofile/package-lock.json
- fieldtofile/package.json
- ics/package-lock.json
- ics/package.json
- intrafox/package-lock.json
- intrafox/package.json
- math/package-lock.json
- math/package.json
- mssql/package-lock.json
- mssql/package.json
- mysql/package-lock.json
- mysql/package.json
- package-lock.json
- package.json
- report/package-lock.json
- report/package.json
- roxFile/package-lock.json
- roxFile/package.json
- sap/package-lock.json
- sap/package.json
- servicetemplate/package-lock.json
- servicetemplate/package.json
- startinstance/package-lock.json
- startinstance/package.json
* Updated
** react
** semantic-ui-react
** @types
** cross-env
** mocha
** typescript
> Updated dependencies

- antragsnr/package-lock.json
- antragsnr/package.json
- buildScript.js
- csv/package-lock.json
- csv/package.json
- fieldtofile/package-lock.json
- fieldtofile/package.json
- ics/package-lock.json
- ics/package.json
- intrafox/package-lock.json
- intrafox/package.json
- math/package-lock.json
- math/package.json
- mssql/package-lock.json
- mssql/package.json
- mysql/package-lock.json
- mysql/package.json
- package-lock.json
- package.json
- report/package-lock.json
- report/package.json
- roxFile/package-lock.json
- roxFile/package.json
- sap/package-lock.json
- sap/package.json
- servicetemplate/package-lock.json
- servicetemplate/package.json
- startinstance/package-lock.json
- startinstance/package.json
* Updates to get fix https://npmjs.com/advisories/1179 in
> Updates transient dependency minimist

- fieldtofile/fieldtofile-service.ts
- roxFile/createroxfile-service.roxtest.ts
- roxFile/createroxfile-service.ts
> Adjusts to new module path structure

- antragsnr/package-lock.json
- antragsnr/package.json
- csv/package-lock.json
- csv/package.json
- ics/package-lock.json
- ics/package.json
- intrafox/package-lock.json
- intrafox/package.json
- math/package-lock.json
- math/package.json
- mssql/package-lock.json
- mssql/package.json
- mysql/package-lock.json
- mysql/package.json
- noop/package-lock.json
- noop/package.json
- report/package-lock.json
- report/package.json
- roxFile/package-lock.json
- roxFile/package.json
- sap/package-lock.json
- sap/package.json
- servicetemplate/package-lock.json
- servicetemplate/package.json
- startinstance/package-lock.json
- startinstance/package.json
> Removes unused @types/hapi__hapi

- package-lock.json
- package.json
* Because @typescript-eslint is now included in the individual projects
Issue: EF-1208
> Removes @typescript-eslint from top-level package.json

- .github/renovate.json
- .github/workflows/Renovate.yml
=> Execute lockfile maintenance after regular Update PRs are merged
> Execute Lockfile Maintenance after 2pm Wednesdays

- .github/renovate.json
- sap/package-lock.json
- sap/package.json
* Add @JPressmar to renovate assignees
* Update @sap/hana-client as previous version has tarball hash mismatch for whatever reason
> Add @JPressmar to renovate assignees

- startinstance/startinstance-service.roxtest.ts
- startinstance/startinstance-service.ts
- startinstance/tsconfig.json
> Activate strictNullChecks for startinstance

- servicetemplate/service1-service.ts
- servicetemplate/service2-service.ts
- servicetemplate/tsconfig.json
> Activate strictNullChecks for servicetemplate

- sap/deleteSAPquery-service.ts
- sap/executeSAPquery-service.ts
- sap/insertSAPquery-service.ts
- sap/sapServiceMethods.ts
- sap/selectSAPquery-service.ts
- sap/tsconfig.json
> Activate strictNullChecks for sap

- math/addition-service.ts
- math/division-service.ts
- math/mathServiceMethods.ts
- math/mathservice.roxtest.ts
- math/multiplikation-service.ts
- math/subtraktion-service.ts
- math/tsconfig.json
> Activate strictNullChecks for math

- mssql/executequery-service.ts
- mssql/executequerynoreturn-service.ts
- mssql/tsconfig.json
> Activate strictNullChecks for mssql

- roxFile/Test/createroxfile-service.roxtest.ts
- roxFile/Test/setroxfilefield-service.roxtest.ts
- roxFile/createroxfile-service.ts
- roxFile/roxtrafileapi.ts
- roxFile/setroxfilefield-service.ts
- roxFile/tsconfig.json
> Activate strictNullChecks for roxfile

- ics/generate-service.ts
- ics/tsconfig.json
> Activate strictNullChecks for ics

- antragsnr/antragsnr-service.ts
- antragsnr/antragsnrservice.roxtest.ts
- antragsnr/errorhelper.ts
- antragsnr/tsconfig.json
> Activate strictNullChecks for antragsnr

- csv/csvServiceMethods.ts
- csv/csvreader-service.ts
- csv/csvservice.roxtest.ts
- csv/projectreader-service.ts
- csv/tsconfig.json
> Activate strictNullChecks for csv

- intrafox/IntrafoxAPI.ts
- intrafox/Test/intrafox-createActivityTest.roxtest.ts
- intrafox/createActivity-service.ts
- intrafox/getActivityByNumber-service.ts
- intrafox/tsconfig.json
> Activate strictNullChecks for intrafox

- mssql/package-lock.json
* Fix https://www.npmjs.com/advisories/1594
> Update @azure/ms-rest-js to version with fixed transient dependency axios

- antragsnr/package-lock.json
- antragsnr/package.json
- buildScript.js
- csv/package-lock.json
- csv/package.json
- ics/package-lock.json
- ics/package.json
- intrafox/package-lock.json
- intrafox/package.json
- math/package-lock.json
- math/package.json
- mssql/package-lock.json
- mssql/package.json
- mysql/package-lock.json
- mysql/package.json
- noop/package-lock.json
- noop/package.json
- package-lock.json
- package.json
- report/package-lock.json
- report/package.json
- roxFile/package-lock.json
- roxFile/package.json
- sap/package-lock.json
- sap/package.json
- servicetemplate/package-lock.json
- servicetemplate/package.json
- startinstance/package-lock.json
- startinstance/package.json
Update to SDK version with strict checks enabled.
> Update SDK to v9.7.0-1

- antragsnr/package.json
- csv/package.json
- ics/package.json
- intrafox/package.json
- math/package.json
- mssql/package.json
- mysql/package.json
- noop/package.json
- package.json
- report/package.json
- roxFile/package.json
- sap/package.json
- servicetemplate/package.json
- startinstance/package.json
* Renovate reads these versions to determine the npm version to use for updates
> Specify node and npm engine versions in package.json

- .github/workflows/trigger_release_creation.yml
- buildScript.js
* Accepts version as input and creates a release with this SDK version
> Add automatic release creation script

- antragsnr/package-lock.json
- antragsnr/package.json
- buildScript.js
- csv/package-lock.json
- csv/package.json
- ics/package-lock.json
- ics/package.json
- intrafox/package-lock.json
- intrafox/package.json
- math/package-lock.json
- math/package.json
- mssql/package-lock.json
- mssql/package.json
- mysql/package-lock.json
- mysql/package.json
- noop/package-lock.json
- noop/package.json
- package-lock.json
- package.json
- report/package-lock.json
- report/package.json
- roxFile/package-lock.json
- roxFile/package.json
- sap/package-lock.json
- sap/package.json
- servicetemplate/package-lock.json
- servicetemplate/package.json
- startinstance/package-lock.json
- startinstance/package.json
> Release v9.9.0-1

- antragsnr/package-lock.json
- antragsnr/package.json
- buildScript.js
- csv/package-lock.json
- csv/package.json
- ics/package-lock.json
- ics/package.json
- intrafox/package-lock.json
- intrafox/package.json
- math/package-lock.json
- math/package.json
- mssql/package-lock.json
- mssql/package.json
- mysql/package-lock.json
- mysql/package.json
- noop/package-lock.json
- noop/package.json
- package-lock.json
- package.json
- report/package-lock.json
- report/package.json
- roxFile/package-lock.json
- roxFile/package.json
- sap/package-lock.json
- sap/package.json
- servicetemplate/package-lock.json
- servicetemplate/package.json
- startinstance/package-lock.json
- startinstance/package.json
> Release v9.9.0-2

- .eslintrc.json
- package-lock.json
- package.json
Relates to https://github.com/roXtra/ProcessHub/pull/1907
> Update eslint-config-prettier to v8

- antragsnr/package-lock.json
- antragsnr/package.json
- buildScript.js
- csv/package-lock.json
- csv/package.json
- ics/package-lock.json
- ics/package.json
- intrafox/package-lock.json
- intrafox/package.json
- math/package-lock.json
- math/package.json
- mssql/package-lock.json
- mssql/package.json
- mysql/package-lock.json
- mysql/package.json
- noop/package-lock.json
- noop/package.json
- package-lock.json
- package.json
- report/package-lock.json
- report/package.json
- roxFile/package-lock.json
- roxFile/package.json
- sap/package-lock.json
- sap/package.json
- servicetemplate/package-lock.json
- servicetemplate/package.json
- startinstance/package-lock.json
- startinstance/package.json
> Release v9.9.0

- antragsnr/package-lock.json
- antragsnr/package.json
- buildScript.js
- csv/package-lock.json
- csv/package.json
- ics/package-lock.json
- ics/package.json
- intrafox/package-lock.json
- intrafox/package.json
- math/package-lock.json
- math/package.json
- mssql/package-lock.json
- mssql/package.json
- mysql/package-lock.json
- mysql/package.json
- noop/package-lock.json
- noop/package.json
- package-lock.json
- package.json
- report/package-lock.json
- report/package.json
- roxFile/package-lock.json
- roxFile/package.json
- sap/package-lock.json
- sap/package.json
- servicetemplate/package-lock.json
- servicetemplate/package.json
- startinstance/package-lock.json
- startinstance/package.json
> Release v9.10.0

- antragsnr/package-lock.json
- antragsnr/package.json
- buildScript.js
- csv/package-lock.json
- csv/package.json
- ics/package-lock.json
- ics/package.json
- intrafox/package-lock.json
- intrafox/package.json
- math/package-lock.json
- math/package.json
- mssql/package-lock.json
- mssql/package.json
- mysql/package-lock.json
- mysql/package.json
- noop/package-lock.json
- noop/package.json
- package-lock.json
- package.json
- report/package-lock.json
- report/package.json
- roxFile/package-lock.json
- roxFile/package.json
- sap/package-lock.json
- sap/package.json
- servicetemplate/package-lock.json
- servicetemplate/package.json
- startinstance/package-lock.json
- startinstance/package.json
> Release v9.11.0

- antragsnr/package-lock.json
- antragsnr/package.json
- buildScript.js
- csv/package-lock.json
- csv/package.json
- ics/package-lock.json
- ics/package.json
- intrafox/package-lock.json
- intrafox/package.json
- math/package-lock.json
- math/package.json
- mssql/package-lock.json
- mssql/package.json
- mysql/package-lock.json
- mysql/package.json
- noop/package-lock.json
- noop/package.json
- package-lock.json
- package.json
- report/package-lock.json
- report/package.json
- roxFile/package-lock.json
- roxFile/package.json
- sap/package-lock.json
- sap/package.json
- servicetemplate/package-lock.json
- servicetemplate/package.json
- startinstance/package-lock.json
- startinstance/package.json
This reverts commit 0b99a4f35b42be01fb8c10a08cf8716afdd1934d, reversing
changes made to b5ee2859ad4eb81d15268f37d491faa988545b9b.
> Revert "Merge pull request #460 from roXtra/release-v9.11.0"

- antragsnr/package-lock.json
- antragsnr/package.json
- buildScript.js
- csv/package-lock.json
- csv/package.json
- ics/package-lock.json
- ics/package.json
- intrafox/package-lock.json
- intrafox/package.json
- math/package-lock.json
- math/package.json
- mssql/package-lock.json
- mssql/package.json
- mysql/package-lock.json
- mysql/package.json
- noop/package-lock.json
- noop/package.json
- package-lock.json
- package.json
- report/package-lock.json
- report/package.json
- roxFile/package-lock.json
- roxFile/package.json
- sap/package-lock.json
- sap/package.json
- servicetemplate/package-lock.json
- servicetemplate/package.json
- startinstance/package-lock.json
- startinstance/package.json
> Release v9.12.0

- antragsnr/package-lock.json
- antragsnr/package.json
- buildScript.js
- csv/package-lock.json
- csv/package.json
- ics/package-lock.json
- ics/package.json
- intrafox/package-lock.json
- intrafox/package.json
- math/package-lock.json
- math/package.json
- mssql/package-lock.json
- mssql/package.json
- mysql/package-lock.json
- mysql/package.json
- noop/package-lock.json
- noop/package.json
- package-lock.json
- package.json
- report/package-lock.json
- report/package.json
- roxFile/package-lock.json
- roxFile/package.json
- sap/package-lock.json
- sap/package.json
- servicetemplate/package-lock.json
- servicetemplate/package.json
- startinstance/package-lock.json
- startinstance/package.json
> Release v9.13.0

- .github/renovate.json
- .github/workflows/Renovate.yml
Temporarily activate renovate today to test lock file maintenance as last update was way back.
> Update renovate, temporarily activate renovate today

- .github/renovate.json
- .github/workflows/Renovate.yml
This reverts commit 7f4e3456505f5b50ae187ee90c794c66a5097231, resets renovate to old schedule
> Revert "Temporarily activate renovate today"

- renovate.config.js
* Adjust to newer renovate version
> Migrate Renovate config

- antragsnr/package-lock.json
- antragsnr/package.json
- buildScript.js
- csv/package-lock.json
- csv/package.json
- ics/package-lock.json
- ics/package.json
- intrafox/package-lock.json
- intrafox/package.json
- math/package-lock.json
- math/package.json
- mssql/package-lock.json
- mssql/package.json
- mysql/package-lock.json
- mysql/package.json
- noop/package-lock.json
- noop/package.json
- package-lock.json
- package.json
- report/package-lock.json
- report/package.json
- roxFile/package-lock.json
- roxFile/package.json
- sap/package-lock.json
- sap/package.json
- servicetemplate/package-lock.json
- servicetemplate/package.json
- startinstance/package-lock.json
- startinstance/package.json
> Release v9.14.0-1

- package-lock.json
- package.json
> Release v9.14.0-2

- package-lock.json
- package.json
> Release v9.14.0-3

- antragsnr/package-lock.json
- antragsnr/package.json
- buildScript.js
- csv/package-lock.json
- csv/package.json
- ics/package-lock.json
- ics/package.json
- intrafox/package-lock.json
- intrafox/package.json
- math/package-lock.json
- math/package.json
- mssql/package-lock.json
- mssql/package.json
- mysql/package-lock.json
- mysql/package.json
- noop/package-lock.json
- noop/package.json
- package-lock.json
- package.json
- report/package-lock.json
- report/package.json
- roxFile/package-lock.json
- roxFile/package.json
- sap/package-lock.json
- sap/package.json
- servicetemplate/package-lock.json
- servicetemplate/package.json
- startinstance/package-lock.json
- startinstance/package.json
> Release v9.14.0

- mysql/main.ts
- mysql/package-lock.json
- mysql/package.json
- mysql/service.json
- mysql/test/mysql.pipelinetest.ts
- mysql/test/mysqlservice.roxtest.ts
- mysql/tsconfig.json
- webpack.config.js
* mysql tests use webpack bundle
> * bundle mysql service with webpack

- roxFile/Test/createroxfile-service.roxtest.ts
- roxFile/createroxfile-service.ts
- server.babel.json
- Add correct node version to server.babel.json
> - Fix roxFile service

- package-lock.json
- package.json
> Release v9.15.0-2

- .github/workflows/Renovate.yml
* Reason: Renovate broke itself
> Update renovate manually

- antragsnr/package-lock.json
- antragsnr/package.json
- buildScript.js
- csv/package-lock.json
- csv/package.json
- ics/package-lock.json
- ics/package.json
- intrafox/package-lock.json
- intrafox/package.json
- math/package-lock.json
- math/package.json
- mssql/package-lock.json
- mssql/package.json
- mysql/package-lock.json
- mysql/package.json
- noop/package-lock.json
- noop/package.json
- package-lock.json
- package.json
- report/package-lock.json
- report/package.json
- roxFile/package-lock.json
- roxFile/package.json
- sap/package-lock.json
- sap/package.json
- servicetemplate/package-lock.json
- servicetemplate/package.json
- startinstance/package-lock.json
- startinstance/package.json
> Release v9.15.0

- antragsnr/package-lock.json
- antragsnr/package.json
- buildScript.js
- csv/package-lock.json
- csv/package.json
- ics/package-lock.json
- ics/package.json
- intrafox/package-lock.json
- intrafox/package.json
- math/package-lock.json
- math/package.json
- mssql/package-lock.json
- mssql/package.json
- mysql/package-lock.json
- mysql/package.json
- noop/package-lock.json
- noop/package.json
- package-lock.json
- package.json
- report/package-lock.json
- report/package.json
- roxFile/package-lock.json
- roxFile/package.json
- sap/package-lock.json
- sap/package.json
- servicetemplate/package-lock.json
- servicetemplate/package.json
- startinstance/package-lock.json
- startinstance/package.json
> Release v9.16.0

- antragsnr/package-lock.json
- antragsnr/package.json
- buildScript.js
- csv/package-lock.json
- csv/package.json
- ics/package-lock.json
- ics/package.json
- intrafox/package-lock.json
- intrafox/package.json
- math/package-lock.json
- math/package.json
- mssql/package-lock.json
- mssql/package.json
- mysql/package-lock.json
- mysql/package.json
- noop/package-lock.json
- noop/package.json
- package-lock.json
- package.json
- report/package-lock.json
- report/package.json
- roxFile/package-lock.json
- roxFile/package.json
- sap/package-lock.json
- sap/package.json
- servicetemplate/package-lock.json
- servicetemplate/package.json
- startinstance/package-lock.json
- startinstance/package.json
> Release v9.17.0

- antragsnr/package-lock.json
- antragsnr/package.json
- buildScript.js
- csv/package-lock.json
- csv/package.json
- ics/package-lock.json
- ics/package.json
- intrafox/package-lock.json
- intrafox/package.json
- math/package-lock.json
- math/package.json
- mssql/package-lock.json
- mssql/package.json
- mysql/package-lock.json
- mysql/package.json
- noop/package-lock.json
- noop/package.json
- package-lock.json
- package.json
- report/package-lock.json
- report/package.json
- roxFile/package-lock.json
- roxFile/package.json
- sap/package-lock.json
- sap/package.json
- servicetemplate/package-lock.json
- servicetemplate/package.json
- startinstance/package-lock.json
- startinstance/package.json
> Release v9.18.0

- antragsnr/package-lock.json
- antragsnr/package.json
- buildScript.js
- csv/package-lock.json
- csv/package.json
- ics/package-lock.json
- ics/package.json
- intrafox/package-lock.json
- intrafox/package.json
- math/package-lock.json
- math/package.json
- mssql/package-lock.json
- mssql/package.json
- mysql/package-lock.json
- mysql/package.json
- noop/package-lock.json
- noop/package.json
- renovate.config.js
- report/package-lock.json
- report/package.json
- roxFile/package-lock.json
- roxFile/package.json
- sap/package-lock.json
- sap/package.json
- servicetemplate/package-lock.json
- servicetemplate/package.json
- startinstance/package-lock.json
- startinstance/package.json
> Updated semantic-ui-react

- antragsnr/package-lock.json
- antragsnr/package.json
- buildScript.js
- csv/package-lock.json
- csv/package.json
- ics/package-lock.json
- ics/package.json
- intrafox/package-lock.json
- intrafox/package.json
- math/package-lock.json
- math/package.json
- mssql/package-lock.json
- mssql/package.json
- mysql/package-lock.json
- mysql/package.json
- noop/package-lock.json
- noop/package.json
- package-lock.json
- package.json
- report/package-lock.json
- report/package.json
- roxFile/package-lock.json
- roxFile/package.json
- sap/package-lock.json
- sap/package.json
- servicetemplate/package-lock.json
- servicetemplate/package.json
- startinstance/package-lock.json
- startinstance/package.json
> Release v9.19.0-1

- antragsnr/package-lock.json
- antragsnr/package.json
- buildScript.js
- csv/package-lock.json
- csv/package.json
- ics/package-lock.json
- ics/package.json
- intrafox/package-lock.json
- intrafox/package.json
- math/package-lock.json
- math/package.json
- mssql/package-lock.json
- mssql/package.json
- mysql/package-lock.json
- mysql/package.json
- noop/package-lock.json
- noop/package.json
- package-lock.json
- package.json
- report/package-lock.json
- report/package.json
- roxFile/package-lock.json
- roxFile/package.json
- sap/package-lock.json
- sap/package.json
- servicetemplate/package-lock.json
- servicetemplate/package.json
- startinstance/package-lock.json
- startinstance/package.json
> Release v9.19.0

- package-lock.json
- package.json
> Release v9.20.0-1

- antragsnr/package-lock.json
- antragsnr/package.json
- buildScript.js
- csv/package-lock.json
- csv/package.json
- ics/package-lock.json
- ics/package.json
- intrafox/package-lock.json
- intrafox/package.json
- math/package-lock.json
- math/package.json
- mssql/package-lock.json
- mssql/package.json
- mysql/package-lock.json
- mysql/package.json
- noop/package-lock.json
- noop/package.json
- package-lock.json
- package.json
- report/package-lock.json
- report/package.json
- roxFile/package-lock.json
- roxFile/package.json
- sap/package-lock.json
- sap/package.json
- servicetemplate/package-lock.json
- servicetemplate/package.json
- startinstance/package-lock.json
- startinstance/package.json
> Release v9.20.0

- antragsnr/package-lock.json
- antragsnr/package.json
- buildScript.js
- csv/package-lock.json
- csv/package.json
- ics/package-lock.json
- ics/package.json
- intrafox/package-lock.json
- intrafox/package.json
- math/package-lock.json
- math/package.json
- mssql/package-lock.json
- mssql/package.json
- mysql/package-lock.json
- mysql/package.json
- noop/package-lock.json
- noop/package.json
- package-lock.json
- package.json
- report/package-lock.json
- report/package.json
- roxFile/package-lock.json
- roxFile/package.json
- sap/package-lock.json
- sap/package.json
- servicetemplate/package-lock.json
- servicetemplate/package.json
- startinstance/package-lock.json
- startinstance/package.json
> Release v9.21.0

- package-lock.json
- package.json
- sap/package-lock.json
> Release v9.22.0

- antragsnr/package-lock.json
- antragsnr/package.json
- buildScript.js
- csv/package-lock.json
- csv/package.json
- ics/package-lock.json
- ics/package.json
- intrafox/package-lock.json
- intrafox/package.json
- math/package-lock.json
- math/package.json
- mssql/package-lock.json
- mssql/package.json
- mysql/package-lock.json
- mysql/package.json
- noop/package-lock.json
- noop/package.json
- package-lock.json
- package.json
- report/package-lock.json
- report/package.json
- roxFile/package-lock.json
- roxFile/package.json
- sap/package-lock.json
- sap/package.json
- servicetemplate/package-lock.json
- servicetemplate/package.json
- startinstance/package-lock.json
- startinstance/package.json
> Release v9.23.0

- antragsnr/package-lock.json
- antragsnr/package.json
- buildScript.js
- csv/package-lock.json
- csv/package.json
- ics/package-lock.json
- ics/package.json
- intrafox/package-lock.json
- intrafox/package.json
- math/package-lock.json
- math/package.json
- mssql/package-lock.json
- mssql/package.json
- mysql/package-lock.json
- mysql/package.json
- noop/package-lock.json
- noop/package.json
- package-lock.json
- package.json
- report/package-lock.json
- report/package.json
- roxFile/package-lock.json
- roxFile/package.json
- sap/package-lock.json
- sap/package.json
- servicetemplate/package-lock.json
- servicetemplate/package.json
- startinstance/package-lock.json
- startinstance/package.json
> Release v9.24.0

- package-lock.json
- package.json
- sap/package-lock.json
> Release v9.30.0-1

- package-lock.json
- package.json
> Release v9.32.0-2

- package-lock.json
- package.json
> Release v9.40.0-2

- setrole/setRoleViaCSV-service.ts
> Use String constructor instead of JSON.stringify

- noop/noop-config.tsx
- noop/noop-service.roxtest.ts
- noop/noop-service.ts
- noop/service.json
- noop/testfiles/noop-test.bpmn
> added option to sleep to noop service

- .github/workflows/trigger_release_creation.yml
* Display checkbox instead of textfield for final release query
> Use boolean value for trigger_release_creation.yml workflow dispatch

- package-lock.json
- package.json
> Release v9.44.0

- package-lock.json
- package.json
> Release v9.52.0-1

- triggerwebhook/service.json
> Set minRoxVersion for Trigger Webhook service to 9.59.0

- package-lock.json
- package.json
> Release v9.60.0-1

- triggerwebhook/triggerwebhook-service.ts
* Enables the usage of instance properties in webhook service data
Issue: EF-3435
> Add instance to triggerwebhook-service

- README.md
- antragsnr/package.json
- csv/package.json
- ics/package.json
- intrafox/package.json
- math/package.json
- mssql/package.json
- mysql/package.json
- noop/package.json
- report/package.json
- roxFile/package.json
- sap/package.json
- servicetemplate/package.json
- setrole/package.json
- setsupervisor/package.json
- startinstance/package.json
- systemsettings/package.json
- triggerwebhook/package.json
* Add config.json explanation to Readme
Issue: EF-3445
> Add possibly present configtemplate.json to final zip

- package-lock.json
- package.json
> Release v9.62.0-1

- ics/generate-config.tsx
- ics/generate-service.ts
- ics/service.json
EF-3439
- added input to define ics file name
- added input for location
- refactored function to also consider time for from and till field
> Add ICS Service input properties for location, fileName etc.

- ics/generate-config.tsx
- ics/generate-service.ts
- ics/service.json
> Use select inputs for all fields in ICS Service

- package-lock.json
- package.json
> Release v9.63.0-2

- package-lock.json
> Fix package-lock.json typescript

- ics/generate-service.ts
> Add correct file ending for ICS service and strip html

- package-lock.json
- package.json
> Release v9.63.0-3

- sap/deleteSAPquery-service.ts
- sap/executeSAPquery-service.ts
- sap/hana-client.d.ts
- sap/insertSAPquery-service.ts
- sap/main.ts
- sap/package-lock.json
- sap/package.json
- sap/sapServiceMethods.ts
- sap/selectSAPquery-service.ts
- sap/service.json
- sap/tsconfig-webpack.json
- sap/tsconfig.json
> Revert "Build sap service using webpack as the other services are", Force deletion of sap service production directory after build

- package-lock.json
- package.json
> Release v9.64.0-4

- package-lock.json
- package.json
> Release v9.65.0-1

- package-lock.json
- package.json
> Release v9.66.0-1

- package-lock.json
- package.json
* Remove @types/node from root project that have been installed as production dependency
> Remove incorrectly installed node types from root project

- package-lock.json
- package.json
> Release v9.72.0-1

- intrafox/IntrafoxAPI.ts
- intrafox/IntrafoxTypes.ts
- intrafox/package-lock.json
- intrafox/package.json
- renovate.config.js
- roxFile/package-lock.json
- roxFile/package.json
- roxFile/roxtrafileapi.ts
- roxFile/roxtrafileapitypes.ts
> replaced node-fetch with axios

- package-lock.json
- package.json
> Release v9.85.0-1

- package-lock.json
- package.json
> Release v9.90.0-1

- package-lock.json
- package.json
> Release v9.90.0-3

- package-lock.json
- package.json
- sap/package-lock.json
> Release v9.90.0-4

- .eslintrc.cjs
- datatable/common.ts
- datatable/main.ts
- datatable/readXlsx.ts
- datatable/readXlsxFromAttachment-test.roxtest.ts
- datatable/readXlsxFromAttachment.ts
- datatable/readXlsxFromAttachmentConfig.tsx
- datatable/service.json
- datatable/testfiles/datatableservice-attachment.bpmn
- datatable/tsconfig.json
> added action to read data table field value from file upload field

- antragsnr/package-lock.json
- antragsnr/package.json
- buildScript.cjs
- csv/package-lock.json
- csv/package.json
- datatable/common.ts
- datatable/package-lock.json
- datatable/package.json
- ics/package-lock.json
- ics/package.json
- intrafox/package-lock.json
- intrafox/package.json
- math/package-lock.json
- math/package.json
- mssql/package-lock.json
- mssql/package.json
- mysql/package-lock.json
- mysql/package.json
- noop/package-lock.json
- noop/package.json
- report/package-lock.json
- report/package.json
- roxFile/package-lock.json
- roxFile/package.json
- sap/package-lock.json
- sap/package.json
> updated sdk

- antragsnr/package-lock.json
- csv/package-lock.json
- datatable/package-lock.json
- ics/package-lock.json
- intrafox/package-lock.json
- math/package-lock.json
- mssql/package-lock.json
- mysql/package-lock.json
- noop/package-lock.json
- package-lock.json
- package.json
- report/package-lock.json
- roxFile/package-lock.json
- sap/package-lock.json
- servicetemplate/package-lock.json
- servicetemplate/package.json
- setrole/package-lock.json
- setrole/package.json
- setsupervisor/package-lock.json
- setsupervisor/package.json
- startinstance/package-lock.json
- startinstance/package.json
- systemsettings/package-lock.json
- systemsettings/package.json
- triggerwebhook/package-lock.json
- triggerwebhook/package.json
> Release v9.90.0-5

- datatable/readXlsxConfig.tsx
- datatable/readXlsxFromAttachmentConfig.tsx
- datatable/readXlsxFromSharepointConfig.tsx
> fixed typo

- antragsnr/package-lock.json
- csv/package-lock.json
- datatable/package-lock.json
- ics/package-lock.json
- intrafox/package-lock.json
- math/package-lock.json
- mssql/package-lock.json
- mysql/package-lock.json
- noop/package-lock.json
- package-lock.json
- package.json
- report/package-lock.json
- roxFile/package-lock.json
- sap/package-lock.json
- sharepoint/package-lock.json
> Release v9.91.0-1

- package-lock.json
- package.json
> Release v9.93.0-1

- .github/renovate.json
> Update renovate assignees

- .github/renovate.json
- .github/workflows/Renovate.yml
> Update renovate schedule

- renovate.config.js
> Remove duplicate schedule from renovate.config.js

- triggerwebhook/service.json
- triggerwebhook/triggerwebhook-config.tsx
- triggerwebhook/triggerwebhook-service.ts
* Add possibility to configure a field where the webhook response is written to in case of a successful request
Issue: IE-7
> Add possibility to write webhook response to field

- report/createReport-config.tsx
> added help for file name field

- skribble/package-lock.json
- skribble/package.json
- skribble/signfile.roxtest.ts
- skribble/signfile.ts
> fixed webhook callback url for skribble service

- datatable/readCsvOrXlsxFromRoxtraFile.ts
https://rossmanith.atlassian.net/browse/RM-503
> switch parameters for getDocumentCall in readXlsxApi
